PetriNet/PetriNet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^objectify/', include('objectify.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

PetriNet/objectify/urls.py
from django.conf.urls import url
from . import views
from views import PetriNetView

urlpatterns = [
     url(r'^add/$', 'objectify.views.add_unit'),
    url(r'^edit/$', PetriNetView.as_view(), name='PetriNetView'),
]

PetriNet/objectify/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
import uuid
# Create your models here.

class Unit(MPTTModel):
    uuid_name = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    human_readable_name = models.CharField(
        max_length=50,
        unique=True
    )

    form = 'O'
    transform = 'L'
    shape_choices = (
        (form, 'Form'),
        (transform,'Transform')
    )
    shape = models.CharField(
        max_length=1,
        choices=shape_choices
    )

    parent = TreeForeignKey(
        'self',
        blank=True,
        null=True,
        related_name='children',
        db_index=True
    )

    # x_val = models.DecimalField(max_digits=13, decimal_places=9, default=0)
    # y_val = models.DecimalField(max_digits=13, decimal_places=9, default=0)
    x_val = models.FloatField(default=0)
    y_val = models.FloatField(default=0)
    class MPTTMeta:
        order_insertion_by = ['human_readable_name']
    def __unicode__(self):
        return self.human_readable_name
class Connection(models.Model):
    source = models.ForeignKey(Unit,related_name='dest')
    destination = models.ForeignKey(Unit,related_name='src')
    def __unicode__(self):
        return '%s to %s' % (self.source, self.destination)

PetriNet/objectify/forms.py
from django.forms import ModelForm,HiddenInput
from django.forms.models import modelformset_factory
from models import Unit,Connection

class AddUnitForm(ModelForm):
    class Meta:
        model = Unit
        exclude = (
            'uuid_name',
            'x_val',
            'y_val',
        )

class SaveUnitForm(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(SaveUnitForm, self).__init__(*args, **kwargs)
    #     self.unitname = self.instance.uuid_name
    class Meta:
        model = Unit
        fields = (
            'x_val',
            'y_val',
        )
        widgets = {
            'x_val':HiddenInput(),
            'y_val':HiddenInput(),
        }


SaveUnitFormSet = modelformset_factory(
    Unit,
    form=SaveUnitForm
)

class AddConnectionForm(ModelForm):
    class Meta:
        model = Connection
        fields = (
            'source',
            'destination',
        )
        widgets = {
            'source':HiddenInput(),
            'destination':HiddenInput(),
        }

PetriNet/objectify/views.py
from django.shortcuts import render,render_to_response,RequestContext
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import TemplateView
from forms import *

from models import Unit,Connection

# Create your views here.

class PetriNetView(TemplateView):
    template_name = 'objectify/main.html'

    def get_context_data(self, **kwargs):
        context = super(PetriNetView, self).get_context_data(**kwargs)
        context['nodes'] = Unit.objects.all()
        context['wires'] = Connection.objects.all()
        context['nodect'] = range(
            max(
                [unit.level for unit in Unit.objects.all()]
            ) + 1
        )
        context['saveUnitSet'] = SaveUnitFormSet()
        context['saveConnSet'] = AddConnectionForm()
        return context
    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        try:
            self.save_unit(self.request.POST)
        except:
            self.save_conn(self.request.POST)
        return self.render_to_response(context)

    def save_unit(self, request):
        formset = SaveUnitFormSet(request)
        if formset.is_valid():
            for form in formset:
                instance = form.save(commit=False)
                # print instance
                if instance.human_readable_name == '':
                    pass
                else:
                    if instance.x_val == \
                        Unit.objects.get(uuid_name=instance.uuid_name).x_val and \
                        instance.y_val == \
                        Unit.objects.get(uuid_name=instance.uuid_name).y_val:
                        pass
                    else:
                        instance.x_val=int(instance.x_val)
                        instance.y_val=int(instance.y_val)
                        # print 'saving %s data:' % instance.human_readable_name
                        # print 'x-val = %f\ny-val = %f' % \
                        #       (instance.x_val,instance.y_val)
                    instance.save()

    def save_conn(self, request):
        form = AddConnectionForm(request)
        if form.is_valid():
            print "Form valid"
            instance = form.save(commit=False)
            new_conn = Connection(source=instance.source,
                                  destination=instance.destination)
            print new_conn.id
            new_conn.save()
            print new_conn.id
            # instance.save()

def add_unit(request):
    if request.method == 'POST':
        print request.POST
        add_unit_form = AddUnitForm(request.POST)
        if add_unit_form.is_valid():
            new_obj = add_unit_form.save(commit=False)
            print new_obj
            new_obj.save()
            return HttpResponseRedirect('/objectify/add/')
    else:
        add_unit_form = AddUnitForm()
    return render(request,
                  'objectify/add_unit.html',
                  {'form':add_unit_form})

PetriNet/objectify/templates/objectify/add_unit.html
<style>
    #add_form{
        background:rgba(10,10,10,.7);
        padding: 5%;
        border-radius: 10px;
    }
    #add_form p{
        color:white;
        width:60px;
    }
    #add_form select{
        width:200px;
    }
    #add_form input{
        width:200px;
</style>
<form name="add_form"
      id="add_form"
      action="/objectify/add/"
      method="post"
      onsubmit="window.parent.location.reload()">
    {% csrf_token %}
    {{ form.human_readable_name.errors }}
    <input id="id_human_readable_name"
           maxlength="50"
           name="human_readable_name"
           type="text"
           placeholder="Name" />
    {{ form.shape.errors }}
    <p>Shape: {{ form.shape }}</p>
    {{ form.parent.errors }}
    <p>Parent: {{ form.parent }}</p>
    <input type="submit" value="Add Unit">
</form>

PetriNet/objectify/templates/objectify/main.html
{% load mptt_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PetriNet Editor</title>
    <!-- STYLE -->
    <link rel="stylesheet"
          type="text/css"
          href="{% static 'objectify/styles.css' %}" />
    <!--End Style-->

    <!-- LIBRARIES -->
    <script src="{% static 'objectify/interact.js' %}"></script>
    <script src="{% static 'objectify/dom.jsPlumb-1.7.6.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
    <script src="{% static 'objectify/jquery.cookie.js' %}"></script>
    <!--End Libraries-->
    <!-- SCRIPTS -->
    <script src="{% static 'objectify/toggleForm.js' %}"></script>
    <script src="{% static 'objectify/descend.js' %}"></script>
    {% include 'objectify/plumbing.js' %}
    <script src="{% static 'objectify/dragaction.js' %}"></script>
    {% include 'objectify/save_unit_submit.js' %}
    {% include 'objectify/visibility.js' %}
    <!--End Scripts-->
</head>

<body>
<div id="toolbar" class="tool">
    <input type="button" value="+" id="add_button">
    <div id="save_conn">
        {% include 'objectify/save_conns.html' %}
    </div>
    <div id="save_unit">
        {% include 'objectify/save_units.html' %}
    </div>
    <div id="add_unit">
        <iframe id="add_u_form" src="/objectify/add" seamless="" height="300" width="300">
        </iframe>
    </div>
    <button id="toggle_connect">D</button>
</div>
<div id="container">
{% recursetree nodes %}
    <div class="draggable"
         id="{{ node.uuid_name }}"
         style="left:{{ node.x_val }}px; top:{{ node.y_val }}px;"
         data-x="{{ node.x_val }}"
         data-y="{{ node.y_val }}">
            <div class="
            {% if node.shape == 'O' %}
            ellipse
            {% elif node.shape == 'L' %}
            rect
            {% endif %}
            level-{{ node.level }}">
                {{ node.human_readable_name }}
        {% if not node.is_leaf_node %}
            {{ children }}
        {% endif %}
            </div>

    </div>
{% endrecursetree %}
</div>
</body>
</html>

PetriNet/objectify/templates/objectify/save_conns.html
<form name="save_conn_form"
      id="save_conn_form"
      action="./"
      method="post">
    {% csrf_token %}
    {{ saveConnSet }}
</form>

PetriNet/objectify/templates/objectify/save_units.html
<form name="save_form"
      action="./"
      method="post"
      onsubmit="return saveUnitSubmit()">
    {% csrf_token %}
    {% for item in saveUnitSet %}
        <div id="{{ item.uuid_name.value }}-x_val">
            {{ item.x_val }}
        </div>

        <div id="{{ item.uuid_name.value }}-y_val">
            {{ item.y_val }}
        </div>
        {{ item.uuid_name }}
    {% endfor %}
    {{ saveUnitSet.management_form }}
    <input type="submit" value="S" id="save_button">
</form>